### ISSUE TITLE
Sync Markdown syntax usage

### ISSUE THREAD

**Issue by beatngu13** [retest/retest-docs#13]
We should sync the way we use Markdown syntax. For instance, sometimes headers use:

```
Header 1
========

Header 2
--------
```

And sometimes:

```
# Header 1

## Header 2
```

Personally, I prefer the latter one.

**Comment by roesslerj** [comment]
What would be the benefit of syncing? Markdown allows both...

**Comment by beatngu13** [comment]
Well, what's the benefit of syncing source code style in general? 😉

**Comment by beatngu13** [comment]
Documentation move to: https://github.com/retest/docs
